version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: events-pgsql
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5442:5432"

  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-consumer:
    image: wurstmeister/kafka:2.13-2.7.0
    command: bash -c "mkdir -vp /tmp/kafka-logs && /opt/kafka_2.13-2.7.0/bin/kafk-console-consumer.sh --zookeeper zookeeper:2181 --from-beginning --topic-name > /tmp/kafka-logs/topic-name.log"
    ports:
      - "9094:9092"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./kafka-1-logs:/tmp/kafka-logs

  wait-for-kafka:
    image: waisbrot/wait
    links:
      - kafka
    environment:
      - TARGETS=kafka:9092
